version: "3.9"
services:
  mongodb:
    image: mongo:5.0.14
    restart: always
    container_name: users-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'erikrios'
      MONGO_INITDB_ROOT_PASSWORD: 'supersecretpassword'
      MONGO_INITDB_DATABASE: 'userservicesdb'
    volumes:
      - mongodb-volume:/data/db
    ports:
      - '27017:27017'
    expose:
      - '27017'
    healthcheck:
      test:
      - CMD
      - mongo
      - --eval
      - "db.adminCommand('ping')"
volumes:
  mongodb-volume:
